#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "atom"
name = "AtoM"
description.en = "Web application for archival description and public access"
description.fr = "Application Web pour la description archivistique et l'accès public"

version = "2.8.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = " AGPL-3.0"
website = "https://www.accesstomemory.org/fr/"
demo = "https://demo.accesstomemory.org/"
userdoc = "https://www.accesstomemory.org/fr/docs/2.8/"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/atom"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://storage.accesstomemory.org/releases/atom-2.8.2.tar.gz"
    sha256 = "98ab91eec0e966c8f7b374ae60e3e18f80e383d608459db9e89dca896f675f4d"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, openjdk-11-jre-headless, imagemagick, ghostscript, poppler-utils, gearman-job-server, php7.4-cli, php7.4-curl, php7.4-json, php7.4-ldap, php7.4-mysql, php7.4-opcache, php7.4-memcache, php7.4-readline, php7.4-xml, php7.4-mbstring, php7.4-xsl php7.4-zip, php7.4-apcu, php-apcu-bc"

    extras.elasticsearch.repo = "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    extras.elasticsearch.key = "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    extras.elasticsearch.packages = "elasticsearch"
    
    [resources.database]
    type = "mysql"

