#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_add_fpm_config

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_systemd_action --service_name="elasticsearch" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing composer dependencies..." --weight=1

ynh_exec_warn_less ynh_install_composer

#=================================================
# APP CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring $app..." --weight=1

# pushd "$install_dir"
# 	php$phpversion symfony tools:install \
# 	  --database-host=localhost \
# 	  --database-port=3306 \
# 	  --database-name=$db_name \
# 	  --database-user=$db_user \
# 	  --database-password=$db_pwd \
# 	  --search-host=127.0.0.1 \
# 	  --search-port=9200 \
# 	  --search-index=atom \
# 	  --site-title=AtoM \
# 	  --site-description='Access to Memory' \
# 	  --site-base-url=http://127.0.0.1 \
# 	  --admin-email=$admin@$domain \
# 	  --admin-username=$admin \
# 	  --admin-password=$password \
# 	  --no-confirmation
# popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
